// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as $$Document from "../bindings/Document.mjs";
import ReactSay from "react-say";
import * as JsxRuntime from "react/jsx-runtime";

import {css} from 'astroturf';
;

function ScribePage(props) {
  var match = React.useState(function (param) {
        return false;
      });
  var setIsBrowser = match[1];
  React.useEffect((function (param) {
          if ($$Document.isBrowser()) {
            Curry._1(setIsBrowser, (function (param) {
                    return true;
                  }));
          }
          
        }), []);
  if (match[0]) {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h1", {
                        children: "Scribe Section"
                      }),
                  JsxRuntime.jsx(ReactSay, {
                        pitch: 1.1,
                        rate: 1.5,
                        volume: 0.8,
                        text: "Hello, this is a test message!"
                      })
                ]
              });
  } else {
    return JsxRuntime.jsx("div", {});
  }
}

var make = ScribePage;

export {
  make ,
}
/*  Not a pure module */
