// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

import {css} from 'astroturf';
;

var navClass = (css`
  @apply p-2 h-12 flex border-b border-gray-200 justify-between items-center text-sm;
`);

var aClass = (css`
  @apply flex items-center w-1/3;
`);

var imgClass = (css`
  @apply w-5;
`);

var spanClass = (css`
  @apply text-xl ml-2 align-middle font-semibold;
`);

var innerSpanClass = (css`
  @apply text-orange-800;
`);

var divClass = (css`
  @apply flex w-2/3 justify-end;
`);

var innerAClass = (css`
  @apply px-3 font-bold;
`);

var legacyAClass = (css`
  @apply px-3;
`);

var mainDivClass = (css`
  @apply flex lg:justify-center;
`);

var mainDivDivClass = (css`
  @apply max-w-5xl w-full lg:w-3/4 text-gray-900 text-base;
`);

var mainDivDivMainClass = (css`
  @apply mt-4 mx-4;
`);

function MainLayout$Navigation(props) {
  return JsxRuntime.jsxs("nav", {
              children: [
                JsxRuntime.jsx(Link, {
                      href: "/",
                      legacyBehavior: true,
                      children: JsxRuntime.jsxs("a", {
                            children: [
                              JsxRuntime.jsx("img", {
                                    className: imgClass,
                                    src: "/static/zeit-black-triangle.svg"
                                  }),
                              JsxRuntime.jsxs("span", {
                                    children: [
                                      "Next",
                                      JsxRuntime.jsx("span", {
                                            children: " + ReScript",
                                            className: innerSpanClass
                                          })
                                    ],
                                    className: spanClass
                                  })
                            ],
                            className: aClass
                          })
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Link, {
                              href: "/",
                              legacyBehavior: true,
                              children: JsxRuntime.jsx("a", {
                                    children: "Home",
                                    className: legacyAClass
                                  })
                            }),
                        JsxRuntime.jsx(Link, {
                              href: "/examples",
                              legacyBehavior: true,
                              children: JsxRuntime.jsx("a", {
                                    children: "Examples",
                                    className: legacyAClass
                                  })
                            }),
                        JsxRuntime.jsx("a", {
                              children: "Github",
                              className: innerAClass,
                              href: "https://github.com/ryyppy/nextjs-default",
                              target: "_blank"
                            })
                      ],
                      className: divClass
                    })
              ],
              className: navClass
            });
}

function MainLayout(props) {
  var minWidth = {
    minWidth: "20rem"
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx(MainLayout$Navigation, {}),
                      JsxRuntime.jsx("main", {
                            children: props.children,
                            className: mainDivDivMainClass
                          })
                    ],
                    className: mainDivDivClass
                  }),
              className: mainDivClass,
              style: minWidth
            });
}

var make = MainLayout;

export {
  make ,
}
/*  Not a pure module */
